export const  logo = require("../images/logo.png")
export const  main = require("../images/mainimg.jpg")
export const  tv = require("../images/tv.png")
export const  device1 = require("../images/device1.png")
export const  video1 = require("../images/video/video-tv.m4v")
export const  mobile = require("../images/mobile.jpg")
export const  children = require("../images/children.png")
